const actionTypes = {
  NEWITEM_UPDATE: 'NEWITEM_UPDATE',
  ITEM_INSERT: 'ITEM_INSERT',
  ITEM_CHECKOUT: 'ITEM_CHECKOUT',
  ITEM_UPDATE: 'ITEM_UPDATE',
  ITEM_REVERT: 'ITEM_REVERT',
  ITEM_CHECKIN: 'ITEM_CHECKIN',
  ITEM_DELETE: 'ITEM_DELETE'
};

export default actionTypes;
