const NEWITEM_UPDATE = 'NEWITEM_UPDATE';

const ITEM_INSERT = 'ITEM_INSERT';
const ITEM_CHECKOUT = 'ITEM_CHECKOUT';
const ITEM_UPDATE = 'ITEM_UPDATE';
const ITEM_REVERT = 'ITEM_REVERT';
const ITEM_CHECKIN = 'ITEM_CHECKIN';
const ITEM_DELETE = 'ITEM_DELETE';

export {NEWITEM_UPDATE, ITEM_INSERT, ITEM_CHECKOUT, ITEM_UPDATE, ITEM_REVERT, ITEM_CHECKIN, ITEM_DELETE};
